POST https://pcfy.redberryinternship.ge/api/laptop/create

Accept: application/json
Content-Type: multipart/form-data

{
    "name": "სსსსსსსსსსსს", 
    "surname": "გგგგგგგ",
    "team_id": 2,
    "position_id": 2,
    "email": "gfasdfg@redberry.ge",
    "token": "3803949bbbced161d9ae347037734b4a",
    "phone_number": "+995555555555",
    "laptop_name": "xps", 
    "laptop_brand_id": 1, 
    "laptop_cpu": "Intel Core i3", 
    "laptop_cpu_cores": 14,
    "laptop_ram": 16,
    "laptop_cpu_threads": 128,
    "laptop_purchase_date": "12-12-2003", 
    "laptop_price": 400,
    "laptop_image": "@_hero_SQ_Dell-XPS-13-Two-in-One-Computer-1-c8f6c090145a4de69ca1c90f75659abe.jpg;type=image/jpeg",
    "laptop_hard_drive_type":"HDD",
    "laptop_state": "new",
}